### ISSUE TITLE
To-Do List: Morning Review 16.06.23

### ISSUE THREAD

**Issue by rmiyoyo** [badger-99/To-Do_List#3]
Hi @badger-99, great work so far working on the project. The app is simple and elegant. I, however, noticed that your code is throwing Stylint linter errors.

**Comment by badger-99** [comment]
Thank you for your feedback! The issue has been solved in [this](https://github.com/badger-99/To-Do_List/pull/2) PR.

Cheers, and happy coding! 🙂
